# Generated by Django 3.1.7 on 2021-03-08 14:33

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório*', max_length=300, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('anexo', models.FileField(blank=True, upload_to='uploads/', verbose_name='Anexo')),
                ('data_expiracao', models.DateField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('mostrar_resultado', models.BooleanField(default=False, verbose_name='Mostrar Resultado')),
                ('opcao_1', djrichtextfield.models.RichTextField(verbose_name='Opção 1')),
                ('opcao_2', djrichtextfield.models.RichTextField(verbose_name='Opção 2')),
                ('opcao_3', djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='Opção 3')),
                ('opcao_4', djrichtextfield.models.RichTextField(blank=True, null=True, verbose_name='Opção 4')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('grupo_usuarios', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Grupo de Usuários')),
            ],
            options={
                'verbose_name': 'Enquete',
                'verbose_name_plural': 'Enquetes',
            },
        ),
    ]
