# Generated by Django 3.1.7 on 2021-04-12 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório*', max_length=300, verbose_name='Título')),
                ('descricao', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Descrição')),
                ('anexo', models.FileField(blank=True, upload_to='uploads/', verbose_name='Anexo')),
                ('data_expiracao', models.DateField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('mostrar_resultado', models.BooleanField(default=False, verbose_name='Mostrar Resultado?')),
                ('voto_unico', models.BooleanField(default=True, verbose_name='Voto Único Por Usuário?')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('grupo_usuarios', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Grupo de Usuários')),
            ],
            options={
                'verbose_name': 'Enquete',
                'verbose_name_plural': 'Enquetes',
            },
        ),
        migrations.CreateModel(
            name='RespostaEnquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True, verbose_name='Opção escolhida:')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('enquete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquetes.enquete', verbose_name='Enquete')),
                ('usuario_votante', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostaenquete_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuário votante')),
            ],
            options={
                'verbose_name': 'Resposta da Enquete',
                'verbose_name_plural': 'Respostas da Enquete',
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', django_quill.fields.QuillField(verbose_name='Título')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('enquete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquetes.enquete', verbose_name='Enquete')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
            },
        ),
    ]
