# Generated by Django 3.1.7 on 2021-03-08 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaEnquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True, verbose_name='Opção escolhida:')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('enquete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquetes.enquete', verbose_name='Enquete')),
                ('usuario_inscricao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Inscrição')),
            ],
            options={
                'verbose_name': 'Resposta da Enquete',
                'verbose_name_plural': 'Respostas da Enquete',
            },
        ),
    ]
