# Generated by Django 3.1.7 on 2021-03-11 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquetes', '0002_respostaenquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaenquete',
            name='usuario_inscricao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostaenquete_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Usuário votante'),
        ),
    ]
