# Generated by Django 3.1.7 on 2021-04-10 19:01

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0002_auto_20210409_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='descricao',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
