# Generated by Django 3.1.7 on 2021-04-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0003_auto_20210410_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquete',
            name='qtd_votos_permitidos',
        ),
        migrations.AddField(
            model_name='enquete',
            name='voto_unico',
            field=models.BooleanField(default=True, verbose_name='Voto Único Por Usuário?'),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='mostrar_resultado',
            field=models.BooleanField(default=False, verbose_name='Mostrar Resultado?'),
        ),
    ]
