# Generated by Django 3.1.7 on 2021-04-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0004_auto_20210416_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostaenquete',
            name='opcao',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Opção escolhida:'),
        ),
    ]
