# Generated by Django 3.1.7 on 2021-04-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0004_auto_20210410_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respostaenquete',
            old_name='usuario_inscricao',
            new_name='usuario_votante',
        ),
    ]
