# Generated by Django 3.1.7 on 2021-04-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0005_auto_20210420_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquete',
            old_name='retrato',
            new_name='foto',
        ),
    ]
