# Generated by Django 2.1.5 on 2020-08-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20200818_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagememail',
            old_name='usuario_criacao',
            new_name='created_by',
        ),
    ]
