# Generated by Django 3.1.7 on 2021-04-28 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('pode_acessar_materiais_didaticos', 'pode_acessar_materiais_didaticos'), ('pode_acessar_boletos_boletins', 'pode_acessar_boletos_boletins'), ('pode_acessar_enquetes', 'pode_acessar_enquetes'), ('pode_acessar_atividades', 'pode_acessar_atividades'), ('pode_acessar_atividades_escolares', 'pode_acessar_atividades_escolares'), ('pode_acessar_informativos', 'pode_acessar_informativos')), 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
