# Generated by Django 3.1.7 on 2021-06-04 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20210503_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cidade_requests_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cidade',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cidade_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dadosbancarios',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dadosbancarios_requests_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dadosbancarios',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dadosbancarios_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estado',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_requests_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estado',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pais',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pais_requests_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pais',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pais_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
