# Generated by Django 2.2.13 on 2020-07-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200710_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dadosbancarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=200, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=200, verbose_name='Agencia')),
                ('operacao', models.IntegerField(verbose_name='Operacao')),
                ('numero_conta', models.CharField(max_length=200, verbose_name='Numero da conta')),
            ],
        ),
    ]
