# Generated by Django 2.2.13 on 2020-07-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dadosbancarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=200, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=200, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pais',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=200, null=True, verbose_name='País'),
        ),
    ]
