# Generated by Django 2.2.13 on 2021-01-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200720_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email'),
        ),
    ]
