# Generated by Django 2.2.13 on 2021-02-19 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20210104_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrointerno',
            name='user',
        ),
        migrations.AddField(
            model_name='registrointerno',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrointerno_requests_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrointerno',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrointerno_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
