# Generated by Django 3.1.7 on 2021-04-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_sigma',
            field=models.CharField(max_length=200, verbose_name='ID Sigma'),
        ),
    ]
