# Generated by Django 2.2.4 on 2020-01-08 14:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='evento',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
