# Generated by Django 2.2.4 on 2020-01-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_auto_20200108_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Início'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_termino',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Término'),
        ),
    ]
