# Generated by Django 3.1.7 on 2021-03-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentacaoObra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório*', max_length=300, verbose_name='Título')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('anexo', models.FileField(blank=True, upload_to='uploads/', verbose_name='Anexo')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('escola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.escola', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Documentação de Obra',
                'verbose_name_plural': 'Documentações de Obra',
            },
        ),
        migrations.CreateModel(
            name='BalancoPatrimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório*', max_length=300, verbose_name='Título')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('anexo', models.FileField(blank=True, upload_to='uploads/', verbose_name='Anexo')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('escola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.escola', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Balanço Patrimonial',
                'verbose_name_plural': 'Balanços Patrimoniais',
            },
        ),
        migrations.CreateModel(
            name='Balancete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório*', max_length=300, verbose_name='Título')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('anexo', models.FileField(blank=True, upload_to='uploads/', verbose_name='Anexo')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('escola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.escola', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Balancete',
                'verbose_name_plural': 'Balancetes',
            },
        ),
    ]
