# Generated by Django 3.1.7 on 2021-04-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('informativos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancete',
            name='grupo_usuarios',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Grupo de Usuários'),
        ),
        migrations.AddField(
            model_name='balancopatrimonial',
            name='grupo_usuarios',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Grupo de Usuários'),
        ),
        migrations.AddField(
            model_name='documentacaoobra',
            name='grupo_usuarios',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Grupo de Usuários'),
        ),
    ]
