# Generated by Django 3.1.7 on 2021-04-24 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informativos', '0006_auto_20210420_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atareuniao',
            name='foto_capa',
        ),
    ]
