# Generated by Django 3.1.7 on 2021-04-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informativos', '0006_auto_20210420_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atareuniao',
            old_name='retrato',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='balancete',
            old_name='retrato',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='balancopatrimonial',
            old_name='retrato',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='documentacaoobra',
            old_name='retrato',
            new_name='foto',
        ),
    ]
