# Generated by Django 3.1.7 on 2021-04-25 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informativos', '0007_remove_atareuniao_foto_capa'),
        ('informativos', '0008_auto_20210422_1036'),
    ]

    operations = [
    ]
