# Generated by Django 3.1.7 on 2021-06-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informativos', '0009_merge_20210424_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentacaoobra',
            options={'verbose_name': 'AEMC Notícia', 'verbose_name_plural': 'AEMC Notícias'},
        ),
    ]
