# Generated by Django 3.1.7 on 2021-06-04 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('informativos', '0010_auto_20210601_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='atareuniao',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atareuniao_requests_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atareuniao',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atareuniao_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balancete',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balancete_requests_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balancete',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balancete_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balancopatrimonial',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balancopatrimonial_requests_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balancopatrimonial',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balancopatrimonial_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentacaoobra',
            name='usuario_atualizacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentacaoobra_requests_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentacaoobra',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentacaoobra_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
