# Generated by Django 3.1.7 on 2021-06-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informativos', '0011_auto_20210604_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancopatrimonial',
            options={'verbose_name': 'Relatório Trimestral', 'verbose_name_plural': 'Relatórios Trimestrais'},
        ),
    ]
