# Generated by Django 3.1.7 on 2021-04-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_auto_20210408_0928'),
        ('atividades_escolares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeescolar',
            name='turmas',
            field=models.ManyToManyField(blank=True, to='escolas.Turma', verbose_name='Turmas'),
        ),
    ]
