# Generated by Django 3.1.7 on 2021-04-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades_escolares', '0002_auto_20210411_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeescolar',
            name='foto_capa',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto de Capa'),
        ),
        migrations.AddField(
            model_name='atividadeescolar',
            name='retrato',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Retrato'),
        ),
    ]
