# Generated by Django 3.1.7 on 2021-04-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_auto_20210408_0928'),
        ('atividades_escolares', '0002_atividadeescolar_turmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeescolar',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.materia', verbose_name='Matéria'),
        ),
    ]
