# Generated by Django 3.1.7 on 2021-04-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades_escolares', '0003_auto_20210420_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividadeescolar',
            old_name='retrato',
            new_name='foto',
        ),
    ]
