# Generated by Django 3.1.7 on 2021-06-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades_escolares', '0006_auto_20210426_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividadeescolar',
            options={'ordering': ['-id'], 'verbose_name': 'Atividade Escolar', 'verbose_name_plural': 'Atividades Escolares'},
        ),
    ]
