# Generated by Django 3.1.7 on 2021-06-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades_escolares', '0008_auto_20210604_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadeescolar',
            name='anexo',
        ),
    ]
