# Generated by Django 3.1.7 on 2021-06-08 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atividades_escolares', '0009_remove_atividadeescolar_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexosAtividadeEscolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório*', max_length=250, verbose_name='Título')),
                ('anexo', models.FileField(blank=True, upload_to='uploads/', verbose_name='Anexo')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('usuario_atualizacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexosatividadeescolar_requests_modified', to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexosatividadeescolar_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo Atividade Escolar',
                'verbose_name_plural': 'Anexos Atividade Escolare',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='atividadeescolar',
            name='anexos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividades_escolares.anexosatividadeescolar', verbose_name='Anexo'),
        ),
    ]
