# Generated by Django 3.1.7 on 2021-06-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividades_escolares', '0011_auto_20210608_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadeescolar',
            name='anexos',
        ),
        migrations.AddField(
            model_name='atividadeescolar',
            name='anexos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividades_escolares.anexosatividadeescolar', verbose_name='Anexo'),
        ),
    ]
