# Generated by Django 3.1.7 on 2021-06-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades_escolares', '0012_auto_20210608_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividadeescolar',
            name='anexos',
        ),
        migrations.AddField(
            model_name='atividadeescolar',
            name='anexos',
            field=models.ManyToManyField(blank=True, to='atividades_escolares.AnexosAtividadeEscolar', verbose_name='Anexo'),
        ),
    ]
