# Generated by Django 3.1.7 on 2021-03-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório*', max_length=250, verbose_name='Título')),
                ('vagas', models.IntegerField(blank=True, null=True, verbose_name='Vagas')),
                ('data_inicial', models.DateField(blank=True, null=True, verbose_name='Data Inicial')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Data Final')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Atividade Extra',
                'verbose_name_plural': 'Atividades Extras',
            },
        ),
        migrations.CreateModel(
            name='AtividadeNoturna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório*', max_length=250, verbose_name='Título')),
                ('vagas', models.IntegerField(blank=True, null=True, verbose_name='Vagas')),
                ('data_inicial', models.DateField(blank=True, null=True, verbose_name='Data Inicial')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Data Final')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Atividade Noturna',
                'verbose_name_plural': 'Atividades Noturnas',
            },
        ),
        migrations.CreateModel(
            name='InscricaoAtividadeExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Inscrição na Atividade Extra',
                'verbose_name_plural': 'Inscrições na Atividade Extra',
            },
        ),
        migrations.CreateModel(
            name='InscricaoAtividadeNoturna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Inscrição na Atividade Noturna',
                'verbose_name_plural': 'Inscrições na Atividade Noturna',
            },
        ),
        migrations.CreateModel(
            name='InscricaoOficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Inscrição na Oficina',
                'verbose_name_plural': 'Inscrições na Oficina',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório*', max_length=250, verbose_name='Título')),
                ('vagas', models.IntegerField(blank=True, null=True, verbose_name='Vagas')),
                ('data_inicial', models.DateField(blank=True, null=True, verbose_name='Data Inicial')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Data Final')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
            },
        ),
    ]
