# Generated by Django 3.1.7 on 2021-03-08 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='turmas',
            field=models.ManyToManyField(blank=True, to='escolas.Turma', verbose_name='Turmas'),
        ),
        migrations.AddField(
            model_name='inscricaooficina',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='inscricaooficina',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividades.oficina', verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='inscricaooficina',
            name='usuario_inscricao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Inscrição'),
        ),
        migrations.AddField(
            model_name='inscricaoatividadenoturna',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='inscricaoatividadenoturna',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividades.oficina', verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='inscricaoatividadenoturna',
            name='usuario_inscricao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Inscrição'),
        ),
        migrations.AddField(
            model_name='inscricaoatividadeextra',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.aluno', verbose_name='Aluno'),
        ),
        migrations.AddField(
            model_name='inscricaoatividadeextra',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividades.oficina', verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='inscricaoatividadeextra',
            name='usuario_inscricao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Inscrição'),
        ),
        migrations.AddField(
            model_name='atividadenoturna',
            name='turmas',
            field=models.ManyToManyField(blank=True, to='escolas.Turma', verbose_name='Turmas'),
        ),
        migrations.AddField(
            model_name='atividadeextra',
            name='turmas',
            field=models.ManyToManyField(blank=True, to='escolas.Turma', verbose_name='Turmas'),
        ),
    ]
