# Generated by Django 3.1.7 on 2021-04-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeextra',
            name='horario',
            field=models.CharField(blank=True, max_length=250, verbose_name='Horário'),
        ),
        migrations.AddField(
            model_name='atividadenoturna',
            name='horario',
            field=models.CharField(blank=True, max_length=250, verbose_name='Horário'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='horario',
            field=models.CharField(blank=True, max_length=250, verbose_name='Horário'),
        ),
    ]
