# Generated by Django 3.1.7 on 2021-03-11 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atividades', '0002_auto_20210308_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricaoatividadeextra',
            name='oficina',
        ),
        migrations.RemoveField(
            model_name='inscricaoatividadenoturna',
            name='oficina',
        ),
        migrations.AddField(
            model_name='inscricaoatividadeextra',
            name='atividade_extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividades.atividadeextra', verbose_name='Atividade Extra'),
        ),
        migrations.AddField(
            model_name='inscricaoatividadenoturna',
            name='atividade_noturna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atividades.atividadenoturna', verbose_name='Atividade Noturna'),
        ),
        migrations.AlterField(
            model_name='inscricaooficina',
            name='usuario_inscricao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário inscrito'),
        ),
    ]
