# Generated by Django 3.1.7 on 2021-04-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_olimpiada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividadeextra',
            old_name='retrato',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='atividadenoturna',
            old_name='retrato',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='oficina',
            old_name='retrato',
            new_name='foto',
        ),
    ]
