# Generated by Django 3.1.7 on 2021-05-24 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0018_auto_20210505_1307'),
        ('atividades', '0006_auto_20210524_1641'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscricaoatividadenoturna',
            unique_together={('aluno', 'atividade_noturna')},
        ),
        migrations.AlterUniqueTogether(
            name='inscricaooficina',
            unique_together={('aluno', 'oficina')},
        ),
    ]
