# Generated by Django 3.1.7 on 2021-11-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0008_auto_20210604_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='inicio_inscricoes',
            field=models.DateTimeField(null=True, verbose_name='Início das Inscrições'),
        ),
    ]
