# Generated by Django 3.1.7 on 2021-11-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0009_oficina_inicio_inscricoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='fim_inscricoes',
            field=models.DateTimeField(null=True, verbose_name='Fim das Inscrições'),
        ),
    ]
