# Generated by Django 3.1.7 on 2021-11-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0010_oficina_fim_inscricoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeextra',
            name='fim_inscricoes',
            field=models.DateTimeField(null=True, verbose_name='Fim das Inscrições'),
        ),
        migrations.AddField(
            model_name='atividadeextra',
            name='inicio_inscricoes',
            field=models.DateTimeField(null=True, verbose_name='Início das Inscrições'),
        ),
        migrations.AddField(
            model_name='atividadenoturna',
            name='fim_inscricoes',
            field=models.DateTimeField(null=True, verbose_name='Fim das Inscrições'),
        ),
        migrations.AddField(
            model_name='atividadenoturna',
            name='inicio_inscricoes',
            field=models.DateTimeField(null=True, verbose_name='Início das Inscrições'),
        ),
    ]
