# Generated by Django 3.1.7 on 2021-04-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_auto_20210413_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(null=True, upload_to='', verbose_name='Retrato'),
        ),
    ]
