# Generated by Django 3.1.7 on 2021-04-21 18:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_auto_20210413_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='hexadecimal',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
