# Generated by Django 3.1.7 on 2021-04-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_auto_20210311_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='qtd_atividades_permitidas',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantidade de Atividades Permitidas'),
        ),
    ]
