# Generated by Django 3.1.7 on 2021-04-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_aluno_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(null=True, upload_to='', verbose_name='Foto'),
        ),
    ]
