# Generated by Django 3.1.7 on 2021-04-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_materia_hexadecimal'),
        ('escolas', '0005_auto_20210421_1129'),
    ]

    operations = [
    ]
