# Generated by Django 3.1.7 on 2021-04-25 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0004_auto_20210424_2058'),
        ('escolas', '0006_merge_20210422_1003'),
    ]

    operations = [
    ]
