# Generated by Django 3.1.7 on 2021-04-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0007_merge_20210424_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='foto_capa',
            field=models.ImageField(null=True, upload_to='', verbose_name='Foto de Capa'),
        ),
    ]
