# Generated by Django 3.1.7 on 2021-04-28 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escolas', '0008_materia_foto_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_aluno', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Usuário do Aluno'),
        ),
    ]
