# Generated by Django 3.1.7 on 2021-04-28 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escolas', '0009_auto_20210428_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_professor', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Usuário do Professor'),
        ),
    ]
