# Generated by Django 3.1.7 on 2021-04-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0011_auto_20210428_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='id_acesso',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Acesso'),
        ),
        migrations.AddField(
            model_name='professor',
            name='id_sigma',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Sigma'),
        ),
        migrations.AddField(
            model_name='professor',
            name='senha',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Senha'),
        ),
    ]
