# Generated by Django 3.1.7 on 2021-04-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0012_auto_20210430_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Usuário'),
        ),
    ]
