# Generated by Django 3.1.7 on 2021-04-30 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20210427_2104'),
        ('escolas', '0013_professor_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.pessoa')),
                ('id_acesso', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Acesso')),
                ('id_sigma', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Sigma')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Usuário')),
                ('senha', models.CharField(blank=True, max_length=200, null=True, verbose_name='Senha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_responsavel', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Usuário do Professor')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
            bases=('core.pessoa',),
        ),
    ]
