# Generated by Django 3.1.7 on 2021-04-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0014_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='id_sigma',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Sigma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='senha',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Senha'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Usuário'),
        ),
    ]
