# Generated by Django 3.1.7 on 2021-05-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0015_auto_20210430_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Usuário'),
        ),
    ]
