# Generated by Django 3.1.7 on 2021-05-05 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escolas', '0017_auto_20210504_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='responsavel4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel4_aluno', to=settings.AUTH_USER_MODEL, verbose_name='Responsável 4'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel5_aluno', to=settings.AUTH_USER_MODEL, verbose_name='Responsável 5'),
        ),
    ]
