# Generated by Django 3.1.7 on 2021-07-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0020_turma_email_pai_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentanteTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pai_representante', models.CharField(max_length=70, verbose_name='Pai representante')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.aluno', verbose_name='Aluno')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Representante de turma',
                'verbose_name_plural': 'Representantes de turma',
            },
        ),
    ]
