# Generated by Django 3.1.7 on 2021-07-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0021_representanteturma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representanteturma',
            name='email',
        ),
        migrations.AddField(
            model_name='representanteturma',
            name='assinatura',
            field=models.EmailField(max_length=254, null=True, verbose_name='Assinatura'),
        ),
    ]
