# Generated by Django 3.1.7 on 2021-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0024_auto_20210722_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representanteturma',
            name='assinatura',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
