# Generated by Django 3.1.7 on 2021-04-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escolas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDidatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório*', max_length=250, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('anexo', models.FileField(blank=True, upload_to='uploads/', verbose_name='Anexo')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('turmas', models.ManyToManyField(blank=True, to='escolas.Turma', verbose_name='Turmas')),
            ],
            options={
                'verbose_name': 'Material Didático',
                'verbose_name_plural': 'Materiais Didáticos',
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório*', max_length=250, verbose_name='Título')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('anexo', models.FileField(blank=True, upload_to='uploads/', verbose_name='Anexo')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('turmas', models.ManyToManyField(blank=True, to='escolas.Turma', verbose_name='Turmas')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
            },
        ),
        migrations.CreateModel(
            name='CalendarioAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório*', max_length=250, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_inicial', models.DateField(blank=True, null=True, verbose_name='Data Inicial')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Data Final')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('turmas', models.ManyToManyField(blank=True, to='escolas.Turma', verbose_name='Turmas')),
            ],
            options={
                'verbose_name': 'Calendário de Atividade',
                'verbose_name_plural': 'Calendário de Atividades',
            },
        ),
        migrations.CreateModel(
            name='AtaReuniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Campo Obrigatório*', max_length=250, verbose_name='Título')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('anexo', models.FileField(blank=True, upload_to='uploads/', verbose_name='Anexo')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('turmas', models.ManyToManyField(blank=True, to='escolas.Turma', verbose_name='Turmas')),
            ],
            options={
                'verbose_name': 'Ata de Reunião',
                'verbose_name_plural': 'Atas de Reuniões',
            },
        ),
    ]
