# Generated by Django 3.1.7 on 2021-04-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtaReuniao',
        ),
    ]
