# Generated by Django 3.1.7 on 2021-04-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0003_auto_20210420_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdidatico',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
