# Generated by Django 3.1.7 on 2021-04-20 19:25

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0005_auto_20210420_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='resumo',
            field=django_quill.fields.QuillField(null=True, verbose_name='Resumo'),
        ),
    ]
