# Generated by Django 3.1.7 on 2021-04-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0006_comunicado_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='foto_capa',
            field=models.ImageField(null=True, upload_to='', verbose_name='Foto de Capa'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='retrato',
            field=models.ImageField(null=True, upload_to='', verbose_name='Retrato'),
        ),
    ]
