# Generated by Django 3.1.7 on 2021-04-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0007_auto_20210421_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarioatividade',
            name='data_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='calendarioatividade',
            name='data_inicial',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Inicial'),
        ),
    ]
