# Generated by Django 3.1.7 on 2021-04-21 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_materia_hexadecimal'),
        ('materiais_didaticos', '0008_auto_20210421_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarioatividade',
            name='materia',
            field=models.ForeignKey(blank=True, help_text='Somente se for relacionado a uma matéria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.materia', verbose_name='Matéria'),
        ),
    ]
