# Generated by Django 3.1.7 on 2021-04-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0008_auto_20210421_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarioatividade',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='foto',
            field=models.ImageField(null=True, upload_to='', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='materialdidatico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto'),
        ),
    ]
