# Generated by Django 3.1.7 on 2021-04-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0009_calendarioatividade_materia'),
        ('materiais_didaticos', '0009_auto_20210421_1105'),
    ]

    operations = [
    ]
