# Generated by Django 3.1.7 on 2021-04-22 13:45

from django.db import migrations, models
import materiais_didaticos.models.tipo_material_didatico


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0010_merge_20210422_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdidatico',
            name='tipo',
            field=models.CharField(blank=True, max_length=250, verbose_name=materiais_didaticos.models.tipo_material_didatico.TipoMaterialDidatico),
        ),
    ]
