# Generated by Django 3.1.7 on 2021-04-24 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0003_materia_hexadecimal'),
        ('materiais_didaticos', '0010_comunicado_usuario_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdidatico',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.materia', verbose_name='Matéria'),
        ),
    ]
