# Generated by Django 3.1.7 on 2021-04-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0011_materialdidatico_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialdidatico',
            name='tipo',
        ),
    ]
