# Generated by Django 3.1.7 on 2021-04-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0012_remove_materialdidatico_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMaterialDidatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Campo Obrigatório*', max_length=250, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Material Didático',
                'verbose_name_plural': 'Tipos de Materiais Didáticos',
            },
        ),
    ]
