# Generated by Django 3.1.7 on 2021-04-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0013_tipomaterialdidatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdidatico',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiais_didaticos.tipomaterialdidatico', verbose_name='Tipo'),
        ),
    ]
