# Generated by Django 3.1.7 on 2021-04-25 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0014_materialdidatico_tipo'),
        ('materiais_didaticos', '0011_materialdidatico_materia'),
    ]

    operations = [
    ]
