# Generated by Django 3.1.7 on 2021-04-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0014_materialdidatico_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomaterialdidatico',
            name='icone',
            field=models.ImageField(default=1, upload_to='tipos_arquivo/', verbose_name='Ícone'),
            preserve_default=False,
        ),
    ]
