# Generated by Django 3.1.7 on 2021-04-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0017_merge_20210426_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialdidatico',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='materialdidatico',
            name='foto_capa',
        ),
    ]
