# Generated by Django 3.1.7 on 2021-05-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0020_midia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midia',
            name='user',
        ),
    ]
