# Generated by Django 3.1.7 on 2021-05-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0021_remove_midia_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='arquivo',
            field=models.FileField(upload_to='midias/', verbose_name='Anexo'),
        ),
    ]
