# Generated by Django 3.1.7 on 2021-06-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_didaticos', '0022_auto_20210527_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicado',
            options={'ordering': ['-id'], 'verbose_name': 'Comunicado', 'verbose_name_plural': 'Comunicados'},
        ),
    ]
